version: '3'

services:
  bridgetown:
    build:
      context: .
      dockerfile: Dockerfile

        # USER_ID: ${USER_ID:-1000}
        # GROUP_ID: ${GROUP_ID:-1000}
        # APP_DIR: ${APP_DIR:-/home/${USER}/bridgetown-app}
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: $GROUP_ID
        APP_DIR: $APP_DIR
        DOCKER_USER: $DOCKER_USER

    command: bash -c "yarn start --host '0.0.0.0'"

      # Not totally necessary to open 4001, but it is used, so lets make it discoverable
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"

      # Volumes cant read ENV variables defined above, so its important to have a fallback
      # This is to seperate host node_modules from docker node_modules
      # This must come after  .:$APP_DIR
    volumes:
      - .:$APP_DIR
      - node_modules:$APP_DIR/node_modules

volumes:
  node_modules:
