version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-user}
        APP_DIR: ${APP_DIR:-/home/user/bridgetown-app}

    command: bash -c "yarn start"

    ports:
      - '4000:4000'

    volumes:
      - .:${APP_DIR:-/home/user/bridgetown-app}
      # this seperates node_modules from the host
      - node_modules:${APP_DIR:-/home/user/bridgetown-app}/node_modules

volumes:
  node_modules:
